# Generated by Django 5.2.17 on 2026-08-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PointTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("point_no", models.IntegerField(unique=True)),
                ("group", models.CharField(max_length=1)),
                ("title_kn", models.CharField(max_length=500)),
                ("title_en", models.CharField(max_length=500)),
                ("columns", models.JSONField()),
            ],
        ),
    ]
