# Generated by Django 5.2.17 on 2026-08-13 08:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0003_entry"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pointtemplate",
            options={"ordering": ["point_no"]},
        ),
    ]
