# Generated by Django 5.2.17 on 2026-08-18 05:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0004_alter_pointtemplate_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pointtemplate",
            options={"ordering": ["id"]},
        ),
    ]
