# Generated by Django 5.2.17 on 2026-08-27 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0005_alter_pointtemplate_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="academic_year",
            field=models.CharField(default=1999, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="entry",
            name="month",
            field=models.CharField(default="May", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="entry",
            unique_together={("school", "point", "month", "academic_year")},
        ),
        migrations.CreateModel(
            name="MonthlySubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.CharField(max_length=20)),
                ("academic_year", models.CharField(max_length=10)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="tracker.school",
                    ),
                ),
            ],
            options={
                "unique_together": {("school", "month", "academic_year")},
            },
        ),
    ]
